export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: 'black',
            color: 'white',
            padding: '1rem'
          }}
        >
          <p>Header</p>
        </header>
        {children}
        <footer>
          <p
            style={{
              backgroundColor: 'black',
              color: 'white',
              padding: '1rem'
            }}
          >
            Footer
          </p>
        </footer>
      </body>
    </html>
  )
}
