export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function ProductDetailsLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {children}
      <h2>Features products</h2>
      {/* Carousel here */}
    </>
  )
}
