export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

function getRandomInt(max: number) {
  return Math.floor(Math.random() * max)
}

export default function ProductDetailsLayout({
  children
}: {
  children: React.ReactNode
}) {
  const random = getRandomInt(2)
  if (random === 1) {
    throw new Error('Something went wrong')
  }
  return (
    <>
      {children}
      <h2>Features products</h2>
      {/* Carousel here */}
    </>
  )
}
